import { Space } from "@/components";
import { CreateWalletScreenProps } from "@/navigators";
import { useAppStore } from "@/stores/appStore";
import { FC } from "react";
import styled from "styled-components/native";
import { Image } from "expo-image";

const Container = styled.View`
  flex: 1;
  padding: 16px;
`;

const Card = styled.TouchableOpacity`
  height: 200px;
  background-color: ${({ theme }) => theme.background.secondary};
  border-radius: 24px;
  padding: 16px;
`;

const Title = styled.Text`
  font-size: 18px;
  font-weight: 600;
  color: ${({ theme }) => theme.foreground.primary};
`;

const Subtitle = styled.Text`
  font-size: 16px;
  color: ${({ theme }) => theme.foreground.tertiary};
  margin-top: 4px;
`;

export const SelectGenerateMethodScreen: FC<
  CreateWalletScreenProps<"SelectGenerateMethod">
> = ({ navigation }) => {
  const appStore = useAppStore();

  async function loginWithGoogle() {
    return appStore.loginWithGoogle();
  }

  function usingPrivateKey() {}

  function usingRecoveryPhrase() {}

  return (
    <Container>
      <Card onPress={loginWithGoogle}>
        <Title>With Google account</Title>
        <Subtitle>Sign in with Google to create your wallet</Subtitle>
        <Image
          source={require("@/assets/images/sign-in-with-google.png")}
          style={{
            width: 320,
            height: 120,
            position: "absolute",
            bottom: 0,
            alignSelf: "center",
          }}
        />
      </Card>
      <Space height={16} />
      <Card onPress={usingPrivateKey}>
        <Title>Using Private Key</Title>
        <Subtitle>A Private Key will be generated by Hyper Wallet</Subtitle>
        <Image
          source={require("@/assets/images/import-private-key.png")}
          style={{
            width: 320,
            height: 120,
            position: "absolute",
            bottom: 0,
            alignSelf: "center",
          }}
        />
      </Card>
      <Space height={16} />
      <Card onPress={usingRecoveryPhrase}>
        <Title>Using Recovery Phrase</Title>
        <Subtitle>A Recovery Phrase will be generated by Hyper Wallet</Subtitle>
        <Image
          source={require("@/assets/images/import-mnemonic.png")}
          style={{
            width: 320,
            height: 100,
            position: "absolute",
            bottom: 0,
            alignSelf: "center",
          }}
        />
      </Card>
    </Container>
  );
};
